controller_list:
  - name: effort_joint_trajectory_controller # j2n7s300
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j2n7s300_joint_1
      - j2n7s300_joint_2
      - j2n7s300_joint_3
      - j2n7s300_joint_4
      - j2n7s300_joint_5
      - j2n7s300_joint_6
      - j2n7s300_joint_7
  - name: effort_finger_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - j2n7s300_joint_finger_1
      - j2n7s300_joint_finger_2
      - j2n7s300_joint_finger_3
  # - name: finger_gripper_controller
  #   action_ns: gripper_command
  #   type: GripperCommand
  #   default: true
  #   joints:
  #     - j2n7s300_joint_finger_1
  #     - j2n7s300_joint_finger_2
  #     - j2n7s300_joint_finger_3
initial:
  - group: arm
    pose: Home
